{
    "name": "Dark Rabbit",
    "version": "18.0.0.1.3",
    "author": "Center of Research and Development",
    "website": "https://crnd.pro",
    "license": "LGPL-3",
    "summary": "Rabbit from the Dark Side can to receive and deliver your messages.",
    "category": "Technical Settings",
    "depends": [
        "generic_background_service",
        "generic_mixin",
    ],
    "demo": [],
    "data": [
        "security/ir.model.access.csv",
        "views/menu.xml",
        "views/connection.xml",
        "views/queue.xml",
        "views/handler.xml",
        "views/event.xml",
        "data/ir_actions_server.xml",
    ],
    "images": ["static/description/banner.png"],
    "installable": True,
    "auto_install": False,
}
